-- Admin users
INSERT INTO users (username, password, email) VALUES
('gamemanager', '$2y$10$w02lkZwIMx5c0JKrJkSNy.owXSWvxHOduhTkelNVIcefsed/j0H9O', 'gamemanager@localhost');

-- Hangman words (kid-friendly with hints)
INSERT INTO hangman_words (word, hint, difficulty) VALUES
('ELEPHANT', 'A massive land mammal known for remarkable memory', 'easy'),
('RAINBOW', 'Seven-color phenomenon formed when sunlight meets raindrops', 'easy'),
('BUTTERFLY', 'Winged insect that completes a dramatic life cycle', 'easy'),
('VOLCANO', 'Geological feature that releases magma from deep underground', 'medium'),
('OCTOPUS', 'Highly intelligent marine animal with multiple flexible limbs', 'easy'),
('STRAWBERRY', 'Small red fruit whose seeds grow on the outside', 'medium'),
('DINOSAUR', 'Extinct reptiles that dominated Earth long before humans', 'easy'),
('SUNFLOWER', 'Tall plant known for turning toward daylight', 'easy'),
('HELICOPTER', 'Aircraft capable of hovering without forward motion', 'medium'),
('CHOCOLATE', 'Sweet food derived from processed cacao', 'easy'),
('PENGUIN', 'Flightless seabird adapted for icy environments', 'easy'),
('WATERFALL', 'Natural feature where a river drops vertically', 'medium'),
('ASTRONAUT', 'Explorer trained to work beyond Earth’s atmosphere', 'medium'),
('PINEAPPLE', 'Tropical fruit with a tough patterned exterior', 'medium'),
('KANGAROO', 'Marsupial famous for powerful leaps', 'medium'),
('SUBMARINE', 'Vehicle designed to operate far below the ocean surface', 'hard'),
('FLAMINGO', 'Wading bird known for long legs and a distinctive pink hue', 'medium'),
('THUNDERSTORM', 'Weather system involving electrical activity in clouds', 'hard'),
('CATERPILLAR', 'Larval stage of a winged insect', 'hard'),
('TRAMPOLINE', 'Elastic surface that stores energy when jumped on', 'hard'),

('METAMORPHOSIS', 'Biological process involving a dramatic change in form', 'hard'),
('COLD WAR', 'Historical rivalry between major global powers after WWII', 'medium'),
('BLACK HOLE', 'Region of space where gravity traps even light', 'hard'),
('RENAISSANCE', 'European era marked by renewed interest in art and knowledge', 'hard'),
('CRYPTOGRAPHY', 'Study of protecting information through secret codes', 'hard'),
('PLATE TECTONICS', 'Scientific explanation for shifting continents', 'hard'),
('SUPPLY CHAIN', 'Network that moves goods from raw materials to customers', 'medium'),
('PANDORAS BOX', 'Mythological symbol for unleashing unexpected trouble', 'medium'),
('QUANTUM LEAP', 'Physics term describing a sudden change at atomic scale', 'hard'),
('ARTIFICIAL INTELLIGENCE', 'Technology focused on machines performing cognitive tasks', 'hard'),
('GREAT DEPRESSION', 'Major worldwide economic crisis beginning in 1929', 'medium'),
('BUTTERFLY EFFECT', 'Idea that tiny changes can produce large outcomes', 'hard'),
('PHOTOSYNTHESIS', 'Process plants use to convert light into stored energy', 'hard'),
('IRON CURTAIN', 'Political boundary dividing Europe during the Cold War era', 'hard'),
('DOUBLE HELIX', 'Shape associated with the structure of DNA', 'hard'),
('TROJAN HORSE', 'Legendary strategy involving hidden entry', 'medium'),
('SILENT MAJORITY', 'Political phrase for a large but quiet group of people', 'hard'),
('THEORY OF RELATIVITY', 'Scientific framework redefining space and time', 'hard'),
('COGNITIVE DISSONANCE', 'Mental discomfort caused by conflicting beliefs', 'hard'),
('FOOLS GOLD', 'Common mineral often mistaken for a valuable metal', 'medium'),

('JELLYFISH', 'Ocean drifter with trailing stingers and a bell-shaped body', 'medium'),
('SNOWFLAKE', 'Frozen crystal that forms unique patterns as it falls', 'medium'),
('LIGHTHOUSE', 'Coastal tower that guides ships at night', 'medium'),
('TELESCOPE', 'Instrument used to observe distant objects in space', 'medium'),
('BACKPACK', 'Portable bag commonly used to carry school supplies', 'easy'),
('DRAGONFLY', 'Fast-flying insect often seen near ponds', 'medium'),
('SANDCASTLE', 'Temporary structure often built on beaches', 'easy'),
('TREASURE', 'Something valuable that people often search for', 'medium'),
('COMPASS', 'Tool used to determine direction when traveling', 'medium'),
('BALLOON', 'Inflated object that can float or be tied to a string', 'easy'),
('NOTEBOOK', 'Collection of blank pages used for writing or drawing', 'easy'),
('HONEYCOMB', 'Wax structure created by bees to store food', 'medium'),
('FIREWORKS', 'Bright nighttime display often used during celebrations', 'medium'),
('IGLOO', 'Dome-shaped shelter built from packed snow', 'medium'),
('SCARECROW', 'Field figure meant to discourage hungry birds', 'medium'),
('MAPLE TREE', 'Tree known for colorful leaves and sweet sap', 'medium'),
('ROLLERCOSTER', 'Amusement ride with steep climbs and sudden drops', 'hard'),
('CONSTELLATION', 'Recognizable pattern formed by groups of stars', 'hard'),
('MICROSCOPE', 'Device that reveals details too small for the naked eye', 'hard'),
('TREBUCHET', 'Medieval machine designed to launch heavy objects', 'hard'),
('AVALANCHE', 'Rapid downhill slide of snow from a mountain slope', 'medium'),
('WINDMILL', 'Structure that uses wind to turn large blades', 'medium'),
('LABYRINTH', 'Complex maze-like pathway designed to confuse travelers', 'hard'),
('SAPPHIRE', 'Precious gemstone commonly associated with a deep blue color', 'medium'),
('ORIGAMI', 'Art form that transforms paper through folding', 'medium'),
('CHAMELEON', 'Reptile famous for changing appearance to match surroundings', 'medium'),
('TIME CAPSULE', 'Container meant to be opened many years in the future', 'medium'),
('MOONLIGHT', 'Natural illumination reflected from Earth’s satellite', 'easy'),
('CAMPFIRE', 'Outdoor fire often used for warmth or cooking', 'easy'),
('STARFISH', 'Marine animal shaped like a star with multiple arms', 'easy');


-- Word Search words (kid-friendly by category)
INSERT INTO word_search_words (word, category) VALUES
('CAT','animals'),
('DOG','animals'),
('FISH','animals'),
('BIRD','animals'),
('FROG','animals'),
('BEAR','animals'),
('LION','animals'),
('DUCK','animals'),
('HORSE','animals'),
('SHARK','animals'),

('APPLE','food'),
('BREAD','food'),
('CANDY','food'),
('PIZZA','food'),
('MANGO','food'),

('SUN','nature'),
('MOON','nature'),
('STAR','nature'),
('RAIN','nature'),
('TREE','nature'),
('CLOUD','nature'),
('FLOWER','nature'),

('BOOK','objects'),
('BALL','objects'),
('KITE','objects'),
('DRUM','objects'),
('BELL','objects'),
('SOCK','objects'),
('HAT','objects'),
('CAKE','objects');

-- Additional Word Search words
INSERT INTO word_search_words (word, category) VALUES

-- Animals
('TIGER','animals'),
('ZEBRA','animals'),
('MONKEY','animals'),
('PANDA','animals'),
('WHALE','animals'),
('DOLPHIN','animals'),
('EAGLE','animals'),
('OWL','animals'),
('FOX','animals'),
('OTTER','animals'),

-- Food
('BANANA','food'),
('ORANGE','food'),
('PEACH','food'),
('CARROT','food'),
('COOKIE','food'),
('CHEESE','food'),
('HONEY','food'),
('PANCAKE','food'),
('WAFFLE','food'),
('NOODLE','food'),

-- Nature
('RIVER','nature'),
('OCEAN','nature'),
('LAKE','nature'),
('ISLAND','nature'),
('FOREST','nature'),
('MOUNTAIN','nature'),
('VALLEY','nature'),
('DESERT','nature'),
('MEADOW','nature'),
('BREEZE','nature'),

-- Objects
('CHAIR','objects'),
('TABLE','objects'),
('PENCIL','objects'),
('CRAYON','objects'),
('MARKER','objects'),
('ERASER','objects'),
('SCISSORS','objects'),
('LANTERN','objects'),
('LADDER','objects'),
('BASKET','objects'),

-- Space
('PLANET','space'),
('COMET','space'),
('GALAXY','space'),
('ASTEROID','space'),
('SATELLITE','space'),
('ROCKET','space'),
('ORBIT','space'),
('METEOR','space'),
('COSMOS','space'),
('NEBULA','space');

-- Additional Word Search words
INSERT INTO word_search_words (word, category) VALUES

-- Animals
('GORILLA','animals'),
('LEOPARD','animals'),
('HYENA','animals'),
('COYOTE','animals'),
('BUFFALO','animals'),
('ANTELOPE','animals'),
('RACCOON','animals'),
('PORCUPINE','animals'),
('PEACOCK','animals'),
('SWAN','animals'),

-- Food
('GRAPES','food'),
('LEMON','food'),
('CHERRY','food'),
('POTATO','food'),
('TOMATO','food'),
('BROCCOLI','food'),
('CUCUMBER','food'),
('MUFFIN','food'),
('BISCUIT','food'),
('PRETZEL','food'),

-- Nature
('GLACIER','nature'),
('CANYON','nature'),
('CLIFF','nature'),
('VOLCANO','nature'),
('WATERFALL','nature'),
('THUNDER','nature'),
('LIGHTNING','nature'),
('HORIZON','nature'),
('SUNRISE','nature'),
('SUNSET','nature'),

-- Objects
('LAPTOP','objects'),
('KEYBOARD','objects'),
('MOUSE','objects'),
('MONITOR','objects'),
('CAMERA','objects'),
('BINOCULARS','objects'),
('TELESCOPE','objects'),
('FLASHLIGHT','objects'),
('SUITCASE','objects'),
('UMBRELLA','objects'),

-- Space
('STARSHIP','space'),
('SPACECRAFT','space'),
('MOONBASE','space'),
('STARDUST','space'),
('SKYLINE','space'),
('AURORA','space'),
('SOLAR','space'),
('LUNAR','space'),
('COSMIC','space'),
('ASTRONAUT','space');